kind: Pod
apiVersion: v1
metadata:
  name: busybox
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ["sh","-c","touch /tmp/healthy && sleep 30 && rm -f /tmp/healthy"]
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "250m"
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 3
