kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  containers:
    - name: app
      image: nginx:latest
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "250m"
