kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "my-service"
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: database
        image: mysql:8.0
        envFrom:
        - secretRef:
            name: my-secret
        ports:
        - containerPort: 3306
          name: db
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 20
          periodSeconds: 10 
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec: 
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi




