kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
  namespace: volumes
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard

